In [30]:
import numpy as np
import pandas as pd
from statsmodels.stats.weightstats import DescrStatsW

In [9]:
np.random.seed(0)
x1_2d = 1.0 + np.random.randn(20, 3)
w1 = np.random.randint(1, 4, 20)
x1_2d, w1

(array([[ 2.76405235,  1.40015721,  1.97873798],
        [ 3.2408932 ,  2.86755799,  0.02272212],
        [ 1.95008842,  0.84864279,  0.89678115],
        [ 1.4105985 ,  1.14404357,  2.45427351],
        [ 1.76103773,  1.12167502,  1.44386323],
        [ 1.33367433,  2.49407907,  0.79484174],
        [ 1.3130677 ,  0.14590426, -1.55298982],
        [ 1.6536186 ,  1.8644362 ,  0.25783498],
        [ 3.26975462, -0.45436567,  1.04575852],
        [ 0.81281615,  2.53277921,  2.46935877],
        [ 1.15494743,  1.37816252,  0.11221425],
        [-0.98079647,  0.65208785,  1.15634897],
        [ 2.23029068,  2.20237985,  0.61267318],
        [ 0.69769725, -0.04855297, -0.42001794],
        [-0.70627019,  2.9507754 ,  0.49034782],
        [ 0.5619257 , -0.25279536,  1.77749036],
        [-0.61389785,  0.78725972,  0.10453344],
        [ 1.3869025 ,  0.48919486, -0.18063218],
        [ 0.97181777,  1.42833187,  1.06651722],
        [ 1.3024719 ,  0.36567791,  0.63725883]]),
 array([3, 2, 3, 3

In [17]:
d1 = DescrStatsW(x1_2d, weights=w1)
d1.mean

array([1.31339743, 1.19573746, 0.86019412])

In [59]:
import scipy.stats as sp

from_csv = pd.read_csv(f'../Data/2020/H20201021dataprat.csv')
print(from_csv)

df = from_csv[['MisparMB','Weight','Net_Work_Prat']]
print(df)

print(df['Net_Work_Prat'].mean())

mesh = DescrStatsW(df['Net_Work_Prat'], weights=df['Weight'])
print(mesh.mean)

# Sample data
# data = np.arange(1,501,1)

# Calculate the 25th, 50th (median), and 75th percentiles
# percentiles = np.arange(10,101,10)

# for percentile in percentiles:
#     # Calculate the percentile value
#     value = np.percentile(data, percentile)

#     # Calculate the percentile boundary
#     boundary = sp.percentileofscore(data, value)

#     print(f"{percentile}th percentile: {value} (Boundary: {boundary}%)")


       S_Seker  MisparMB  ...  Able_To_Start_A_Job  Work_Last_3_Month
0         2020     14449  ...                  NaN                1.0
1         2020     14450  ...                  NaN                2.0
2         2020     14451  ...                  NaN                1.0
3         2020     14451  ...                  NaN                2.0
4         2020     14451  ...                  NaN                NaN
...        ...       ...  ...                  ...                ...
18232     2020     50475  ...                  NaN                1.0
18233     2020     50476  ...                  NaN                2.0
18234     2020     50476  ...                  NaN                2.0
18235     2020     50476  ...                  NaN                1.0
18236     2020     50476  ...                  NaN                2.0

[18237 rows x 82 columns]
       MisparMB    Weight  Net_Work_Prat
0         14449  1684.705           9504
1         14450  1085.435              0
2         